# Generated by Django 3.0.5 on 2020-06-01 13:45

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '__first__'),
        ('medium', '__first__'),
        ('country', '__first__'),
        ('state', '__first__'),
        ('board', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=255)),
                ('class_label', models.CharField(blank=True, max_length=100, null=True)),
                ('division_label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_label', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=12)),
                ('dias_number', models.CharField(max_length=50)),
                ('school_logo', models.FileField(blank=True, upload_to=school.models.get_image_filename)),
                ('about_school', models.TextField(max_length=1000)),
                ('iml_school_code', models.CharField(max_length=100)),
                ('commission_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50)),
                ('commission_value', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=50)),
                ('school_board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.Board')),
                ('school_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='city.City')),
                ('school_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.Country')),
                ('school_medium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medium.Medium')),
                ('school_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='state.State')),
            ],
        ),
    ]
