# Generated by Django 3.0.5 on 2020-06-01 13:45

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, upload_to=school.models.get_image_filename),
        ),
    ]
