# Generated by Django 3.0.5 on 2020-06-02 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0005_auto_20200601_1437'),
        ('class_master', '__first__'),
        ('state', '__first__'),
        ('country', '__first__'),
        ('city', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('profile_picture', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('roll_number', models.IntegerField()),
                ('gr_number', models.IntegerField()),
                ('student_address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_master.class_master')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.School')),
                ('student_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='city.City')),
                ('student_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.Country')),
                ('student_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='state.State')),
            ],
        ),
    ]
