# Generated by Django 3.0.5 on 2020-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='media/profile/', verbose_name='profile_pic'),
        ),
    ]
