# Generated by Django 3.0.5 on 2020-06-05 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('division', '0002_auto_20200521_0650'),
        ('class_master', '__first__'),
        ('school', '0005_auto_20200601_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='resource_title')),
                ('description', models.CharField(max_length=1000, verbose_name='resource_description')),
                ('file_media', models.FileField(upload_to='media/resources/', verbose_name='resource_file')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.content_type')),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_data', models.CharField(max_length=20000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_master', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_master', to='class_master.class_master')),
                ('division_master', models.ManyToManyField(blank=True, default=None, null=True, related_name='division', to='division.Division')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resource')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='school.School')),
                ('subject_master', models.ManyToManyField(blank=True, default=None, null=True, related_name='subject', to='subject.Subject', verbose_name='subject_id')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
