# Generated by Django 3.0.5 on 2020-05-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('student', '__first__'),
        ('division', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('school_division', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='division.school_division_mapping')),
                ('student_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
                ('teacher_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher')),
            ],
        ),
    ]
